# Generated by Django 5.2.7 on 2025-10-30 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=64)),
                ('url', models.CharField(max_length=128)),
            ],
        ),
    ]
