# Generated by Django 5.2.7 on 2025-10-30 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('fighters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bout', models.CharField(max_length=128)),
                ('outcome', models.CharField(max_length=8)),
                ('weight_class', models.CharField(max_length=128)),
                ('method', models.CharField(max_length=32)),
                ('round', models.IntegerField()),
                ('time', models.CharField(max_length=8)),
                ('time_format', models.CharField(max_length=32)),
                ('referee', models.CharField(max_length=32, null=True)),
                ('details', models.CharField(max_length=256, null=True)),
                ('url', models.CharField(max_length=128)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fights', to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='FightStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('knockdowns', models.IntegerField()),
                ('submission_attempts', models.IntegerField()),
                ('reversals', models.IntegerField()),
                ('control_time', models.IntegerField()),
                ('takedowns', models.IntegerField()),
                ('takedowns_attempted', models.IntegerField()),
                ('total_strikes', models.IntegerField()),
                ('total_strikes_attempted', models.IntegerField()),
                ('sig_strikes', models.IntegerField()),
                ('sig_strikes_attempted', models.IntegerField()),
                ('head_strikes', models.IntegerField()),
                ('head_strikes_attempted', models.IntegerField()),
                ('body_strikes', models.IntegerField()),
                ('body_strikes_attempted', models.IntegerField()),
                ('leg_strikes', models.IntegerField()),
                ('leg_strikes_attemped', models.IntegerField()),
                ('distance_strikes', models.IntegerField()),
                ('distance_strikes_attempted', models.IntegerField()),
                ('clinch_strikes', models.IntegerField()),
                ('clinch_strikes_attempted', models.IntegerField()),
                ('ground_strikes', models.IntegerField()),
                ('ground_strikes_attemped', models.IntegerField()),
                ('fight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='fights.fight')),
                ('fighter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='fighters.fighter')),
            ],
        ),
    ]
